# Generated by Django 4.2.4 on 2024-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/product/')),
                ('descript', models.CharField(max_length=221)),
            ],
        ),
    ]
